version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - storefront-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"

volumes:
  storefront-postgres-data:
    external: true
